apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  namespace: vsandevstg-shorturl
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 2
  template:
    metadata:
      labels:
        app: url-shortener
        environment: stage
    spec:
      securityContext:
        runAsUser: 175345366
        runAsGroup: 201
        fsGroup: 201
      containers:
      - name: url-shortener
        image: vsaninternaltools-docker-local.artifactory.vcfd.broadcom.net/stage/shorturl/server-stg:latest
        env:
          - name: STAGE
            value: "stage"
          - name: SHORT_KEY_GENERATION_RETRIES_COUNT
            value: "5"
          - name: SHORT_URL_LENGTH
            value: "5"
          - name: ALIAS_URL_MIN_LENGTH
            value: "5"
          - name: ALIAS_URL_MAX_LENGTH
            value: "16"
          - name: SHORT_KEY_PREFIX
            value: "https://vsanvia.vdp-stg.lvn.broadcom.net/"
          - name: REDIS_OM_URL
            value: "redis://shorturl:shorturl@redis-stack-server-master.vsandevstg-shorturl.svc.cluster.local:6379"
          - name: PORT
            value: "5000"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        volumeMounts:
        - name: log-volume
          mountPath: /url-shortener/persist
      volumes:
      - name: log-volume
        nfs:
          path: /dbc/lvn-dbc2403/xl061876/public_html/url-shortener/persist
          server: lvn-dbc2403.lvn.broadcom.net
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-svc
  namespace: vsandevstg-shorturl
spec:
  selector:
    app: url-shortener
  ports:
  - protocol: TCP
    port: 443
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: url-shortener-httpproxy
  namespace: vsandevstg-shorturl
  annotations:
    kubernetes.io/ingress.class: "vdp-contour-int"
spec:
  virtualhost:
    fqdn: vsanvia.vdp-stg.lvn.broadcom.net
    tls:
      secretName: infra-system/vdp-int-domain-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: url-shortener-svc
          port: 443
      timeoutPolicy:
        response: 480s
