apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  namespace: vsanperf-shorturl
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 1
  template:
    metadata:
      labels:
        app: url-shortener
        environment: product
    spec:
      securityContext:
        runAsUser: 175345366
        runAsGroup: 201
        fsGroup: 201
      containers:
        - name: url-shortener
          image: vsaninternaltools-docker-local.artifactory.vcfd.broadcom.net/product/slackbot/url-shortener:vdp
          env:
            - name: STAGE
              value: "product"
            - name: SHORT_KEY_GENERATION_RETRIES_COUNT
              value: "5"
            - name: SHORT_URL_LENGTH
              value: "5"
            - name: ALIAS_URL_MIN_LENGTH
              value: "5"
            - name: ALIAS_URL_MAX_LENGTH
              value: "16"
            - name: SHORT_KEY_PREFIX
              value: "https://vsanvia.broadcom.net/"
            - name: REDIS_OM_URL
              value: "redis://shorturl:shorturl@redis-stack-server-master.vsanperf-shorturl.svc.cluster.local:6379"
            - name: PORT
              value: "5000"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-svc
  namespace: vsanperf-shorturl
spec:
  selector:
    app: url-shortener
  ports:
  - port: 443
    targetPort: 5000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: url-shortener-httpproxy
  namespace: vsanperf-shorturl
  annotations:
    kubernetes.io/ingress.class: "vdp-contour-int"
spec:
  virtualhost:
    fqdn: vsanvia.vdp.lvn.broadcom.net
    tls:
      secretName: infra-system/vdp-int-domain-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: url-shortener-svc
          port: 443
      timeoutPolicy:
        response: 480s
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: url-shortener-cname
  namespace: vsanperf-shorturl
  generation: 2
  annotations:
    kubernetes.io/ingress.class: "vdp-contour-int"
spec:
  virtualhost:
    fqdn: vsanvia.broadcom.net
    tls:
      secretName: infra-system/vdp-int-domain-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: url-shortener-svc
          port: 443
      timeoutPolicy:
        response: 480s