apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: vsanperf-external-database
spec:
  type: NodePort
  selector:
    app: redis-stack
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stack
  namespace: vsanperf-external-database
spec:
  selector:
    matchLabels:
      app: redis-stack
      environment: product
  serviceName: "redis-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-stack
        environment: product
        sidecar.istio.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-stack
        image: vsaninternaltools-docker-local.artifactory.vcfd.broadcom.net/product/slackbot/redis-stack:latest
        env:
        - name: REDIS_PASSWORD
          value: 'shorturl'
        command: ["redis-stack-server"]
        args:
          - "--bind 0.0.0.0"
          - "--requirepass ${REDIS_PASSWORD}"
          - "--user shorturl >${REDIS_PASSWORD}"
          - "--save 3600 1 300 100 60 10000"
          - "--appendonly yes"
          - "--appendfilename appendonly.aof"
          - "--appendfsync everysec"
          - "--dir /data"
          - "--logfile /data/redis.log"
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-db-storage
            mountPath: /data
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
  volumeClaimTemplates:
  - metadata:
      name: redis-db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: tier0
      resources:
        requests:
          storage: 50Gi
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: redis-gateway
  namespace: vsanperf-external-database
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - vsanperf-shorturl-db.vdp.lvn.broadcom.net
    port:
      name: redis
      number: 6379
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redis-virtualservice
  namespace: vsanperf-external-database
spec:
  gateways:
  - redis-gateway
  hosts:
  - vsanperf-shorturl-db.vdp.lvn.broadcom.net
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: redis-svc
        port:
          number: 6379